"""Rezervasyon modeline tur_paketi_id eklendi

Revision ID: 0b1293a48d11
Revises: 2294d293dde3
Create Date: 2025-04-27 20:31:35.675478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1293a48d11'
down_revision = '2294d293dde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rezervasyonlar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tur_paketi_id', sa.Integer(), nullable=True))
        batch_op.alter_column('tur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tur_paketleri', ['tur_paketi_id'], ['id'])

    with op.batch_alter_table('tur_paketleri', schema=None) as batch_op:
        batch_op.drop_constraint('tur_paketleri_baslangic_destinasyon_id_fkey', type_='foreignkey')
        batch_op.drop_column('baslangic_destinasyon_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tur_paketleri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baslangic_destinasyon_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tur_paketleri_baslangic_destinasyon_id_fkey', 'destinasyonlar', ['baslangic_destinasyon_id'], ['id'])

    with op.batch_alter_table('rezervasyonlar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tur_paketi_id')

    # ### end Alembic commands ###
