"""Degerlendirme modülü eklendi

Revision ID: 486c97c4930b
Revises: 6eef5b6cf30b
Create Date: 2025-04-20 12:34:56.655940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486c97c4930b'
down_revision = '6eef5b6cf30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degerlendirmeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('tur_paketi_id', sa.Integer(), nullable=False),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('yorum', sa.Text(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.ForeignKeyConstraint(['tur_paketi_id'], ['tur_paketleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('degerlendirmeler')
    # ### end Alembic commands ###
