"""değerlendirme modeline tur_id eklendi

Revision ID: 628c36810a3a
Revises: abd184d5109b
Create Date: 2025-04-27 13:16:39.184039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628c36810a3a'
down_revision = 'abd184d5109b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('degerlendirmeler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tur_id', sa.Integer(), nullable=True))
        batch_op.alter_column('tur_paketi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tur', ['tur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('degerlendirmeler', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tur_paketi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tur_id')

    # ### end Alembic commands ###
