"""Initial migration

Revision ID: 6b8dc8601eb4
Revises: 
Create Date: 2025-04-27 06:25:18.756714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8dc8601eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ulke', sa.String(length=100), nullable=True),
    sa.Column('sehir', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.String(length=200), nullable=True),
    sa.Column('enlem', sa.Float(), nullable=True),
    sa.Column('boylam', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['destinasyonlar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musteriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('soyad', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('adres', sa.String(length=200), nullable=True),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('dil_bilgisi', sa.String(length=200), nullable=True),
    sa.Column('deneyim_yili', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('surucu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('ehliyet_no', sa.String(length=50), nullable=False),
    sa.Column('ehliyet_sinifi', sa.String(length=20), nullable=True),
    sa.Column('deneyim_yil', sa.Integer(), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('uyruk', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=200), nullable=False),
    sa.Column('sure', sa.String(length=50), nullable=False),
    sa.Column('fiyat', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('resim', sa.String(length=200), nullable=True),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('destinasyon_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destinasyon_id'], ['destinasyonlar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('surucu_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['surucu_id'], ['surucu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('tur_paketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('sure', sa.String(length=50), nullable=True),
    sa.Column('fiyat', sa.Float(), nullable=False),
    sa.Column('kar', sa.Float(), nullable=False),
    sa.Column('kapasite', sa.Integer(), nullable=True),
    sa.Column('baslangic_destinasyon_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('surucu_id', sa.Integer(), nullable=True),
    sa.Column('rehber_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tur_tarihi', sa.Date(), nullable=True),
    sa.Column('resim_url', sa.String(length=255), nullable=True),
    sa.Column('destinasyon_detay', sa.String(length=100), nullable=True),
    sa.Column('max_katilimci', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baslangic_destinasyon_id'], ['destinasyonlar.id'], ),
    sa.ForeignKeyConstraint(['rehber_id'], ['rehber.id'], ),
    sa.ForeignKeyConstraint(['surucu_id'], ['surucu.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tur_seferi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tur_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('kontenjan', sa.Integer(), nullable=True),
    sa.Column('kalan_kontenjan', sa.Integer(), nullable=True),
    sa.Column('fiyat', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tur_id'], ['tur.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('degerlendirmeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('tur_paketi_id', sa.Integer(), nullable=False),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('yorum', sa.Text(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.ForeignKeyConstraint(['tur_paketi_id'], ['tur_paketleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rezervasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tur_id', sa.Integer(), nullable=False),
    sa.Column('tur_sefer_id', sa.Integer(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('kisi_sayisi', sa.Integer(), nullable=False),
    sa.Column('oda_tipi', sa.String(length=50), nullable=True),
    sa.Column('ozel_istekler', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.ForeignKeyConstraint(['tur_id'], ['tur.id'], ),
    sa.ForeignKeyConstraint(['tur_sefer_id'], ['tur_seferi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tur_destinasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tur_paketi_id', sa.Integer(), nullable=False),
    sa.Column('destinasyon_id', sa.Integer(), nullable=False),
    sa.Column('siralama', sa.Integer(), nullable=True),
    sa.Column('kalma_suresi', sa.Integer(), nullable=True),
    sa.Column('not_bilgisi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destinasyon_id'], ['destinasyonlar.id'], ),
    sa.ForeignKeyConstraint(['tur_paketi_id'], ['tur_paketleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tur_destinasyonlar')
    op.drop_table('rezervasyonlar')
    op.drop_table('degerlendirmeler')
    op.drop_table('tur_seferi')
    op.drop_table('tur_paketleri')
    op.drop_table('vehicles')
    op.drop_table('tur')
    op.drop_table('user')
    op.drop_table('surucu')
    op.drop_table('rehber')
    op.drop_table('musteriler')
    op.drop_table('destinasyonlar')
    # ### end Alembic commands ###
