"""Müşteri ve rezervasyon modülleri eklendi

Revision ID: 6eef5b6cf30b
Revises: e78fb89abfaa
Create Date: 2025-04-20 12:30:37.459272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eef5b6cf30b'
down_revision = 'e78fb89abfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musteriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('soyad', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('adres', sa.String(length=200), nullable=True),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rezervasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=False),
    sa.Column('tur_seferi_id', sa.Integer(), nullable=False),
    sa.Column('kisi_sayisi', sa.Integer(), nullable=True),
    sa.Column('toplam_fiyat', sa.Float(), nullable=True),
    sa.Column('rezervasyon_tarihi', sa.DateTime(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('odeme_durumu', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.ForeignKeyConstraint(['tur_seferi_id'], ['tur_seferleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rezervasyonlar')
    op.drop_table('musteriler')
    # ### end Alembic commands ###
