"""İlk migrasyon

Revision ID: 7083fe5f5df4
Revises: 
Create Date: 2025-04-20 09:58:42.707197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7083fe5f5df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bolgeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ulke', sa.String(length=100), nullable=True),
    sa.Column('sehir', sa.String(length=100), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('destinasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bolge_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('tur', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('adres', sa.String(length=200), nullable=True),
    sa.Column('fiyat', sa.Float(), nullable=True),
    sa.Column('enlem', sa.Float(), nullable=True),
    sa.Column('boylam', sa.Float(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bolge_id'], ['bolgeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destinasyonlar')
    op.drop_table('user')
    op.drop_table('bolgeler')
    # ### end Alembic commands ###
