"""Add tour profit, driver and car type models

Revision ID: a737edd2c628
Revises: c25c918555db
Create Date: 2025-04-26 10:08:39.430071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a737edd2c628'
down_revision = 'c25c918555db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, drop the foreign key constraint from rezervasyonlar to tur_seferleri
    with op.batch_alter_table('rezervasyonlar', schema=None) as batch_op:
        batch_op.drop_constraint('rezervasyonlar_tur_seferi_id_fkey', type_='foreignkey')
        
    # Now we can safely drop the tur_seferleri table
    op.create_table('konum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('ulke', sa.String(length=100), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rehber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('dil_bilgisi', sa.String(length=200), nullable=True),
    sa.Column('deneyim_yili', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('surucu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('ehliyet_no', sa.String(length=50), nullable=False),
    sa.Column('ehliyet_sinifi', sa.String(length=20), nullable=True),
    sa.Column('deneyim_yil', sa.Integer(), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('uyruk', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=200), nullable=False),
    sa.Column('sure', sa.String(length=50), nullable=False),
    sa.Column('fiyat', sa.Float(), nullable=False),
    sa.Column('kar', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('resim', sa.String(length=200), nullable=True),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('konum_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('arac_tipi', sa.String(length=100), nullable=True),
    sa.Column('surucu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['konum_id'], ['konum.id'], ),
    sa.ForeignKeyConstraint(['surucu_id'], ['surucu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tur_seferi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tur_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('kontenjan', sa.Integer(), nullable=True),
    sa.Column('kalan_kontenjan', sa.Integer(), nullable=True),
    sa.Column('fiyat', sa.Float(), nullable=True),
    sa.Column('kar', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('rehber_id', sa.Integer(), nullable=True),
    sa.Column('surucu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rehber_id'], ['rehber.id'], ),
    sa.ForeignKeyConstraint(['surucu_id'], ['surucu.id'], ),
    sa.ForeignKeyConstraint(['tur_id'], ['tur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Now drop the table after constraints are gone
    op.drop_table('tur_seferleri')
    
    with op.batch_alter_table('musteriler', schema=None) as batch_op:
        batch_op.drop_constraint('musteriler_email_key', type_='unique')

    with op.batch_alter_table('rezervasyonlar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tur_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tur_sefer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ad', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('soyad', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('telefon', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tarih', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('oda_tipi', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ozel_istekler', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True))
        batch_op.alter_column('musteri_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('kisi_sayisi',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('durum',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        # Foreign key constraint is already dropped at the beginning
        batch_op.create_foreign_key(None, 'tur', ['tur_id'], ['id'])
        batch_op.create_foreign_key(None, 'tur_seferi', ['tur_sefer_id'], ['id'])
        batch_op.drop_column('toplam_fiyat')
        batch_op.drop_column('rezervasyon_tarihi')
        batch_op.drop_column('odeme_durumu')
        batch_op.drop_column('tur_seferi_id')

    with op.batch_alter_table('tur_paketleri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('surucu_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('arac_tipi', sa.String(length=100), nullable=True))
        batch_op.alter_column('ad',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('sure',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'surucu', ['surucu_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('tur_paketleri', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sure',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ad',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('arac_tipi')
        batch_op.drop_column('surucu_id')
        batch_op.drop_column('kar')

    with op.batch_alter_table('rezervasyonlar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tur_seferi_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('odeme_durumu', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rezervasyon_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('toplam_fiyat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rezervasyonlar_tur_seferi_id_fkey', 'tur_seferleri', ['tur_seferi_id'], ['id'])
        batch_op.alter_column('durum',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('kisi_sayisi',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('musteri_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('olusturma_tarihi')
        batch_op.drop_column('ozel_istekler')
        batch_op.drop_column('oda_tipi')
        batch_op.drop_column('tarih')
        batch_op.drop_column('telefon')
        batch_op.drop_column('email')
        batch_op.drop_column('soyad')
        batch_op.drop_column('ad')
        batch_op.drop_column('tur_sefer_id')
        batch_op.drop_column('tur_id')

    with op.batch_alter_table('musteriler', schema=None) as batch_op:
        batch_op.create_unique_constraint('musteriler_email_key', ['email'])

    op.create_table('tur_seferleri',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tur_paketi_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('baslangic_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('bitis_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('arac_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rehber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sofor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('durum', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('olusturma_tarihi', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['arac_id'], ['araclar.id'], name='tur_seferleri_arac_id_fkey'),
    sa.ForeignKeyConstraint(['rehber_id'], ['personel.id'], name='tur_seferleri_rehber_id_fkey'),
    sa.ForeignKeyConstraint(['sofor_id'], ['personel.id'], name='tur_seferleri_sofor_id_fkey'),
    sa.ForeignKeyConstraint(['tur_paketi_id'], ['tur_paketleri.id'], name='tur_seferleri_tur_paketi_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tur_seferleri_pkey')
    )
    op.drop_table('tur_seferi')
    op.drop_table('tur')
    op.drop_table('surucu')
    op.drop_table('rehber')
    op.drop_table('konum')
    # ### end Alembic commands ###
