"""Kaynak modülleri eklendi

Revision ID: c2caa668eb0f
Revises: 7083fe5f5df4
Create Date: 2025-04-20 10:26:08.479933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2caa668eb0f'
down_revision = '7083fe5f5df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('araclar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaka', sa.String(length=20), nullable=False),
    sa.Column('arac_turu', sa.String(length=50), nullable=True),
    sa.Column('koltuk_sayisi', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaka')
    )
    op.create_table('personel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('soyad', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('pozisyon', sa.String(length=50), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personel')
    op.drop_table('araclar')
    # ### end Alembic commands ###
