"""Tur modülleri eklendi

Revision ID: e78fb89abfaa
Revises: c2caa668eb0f
Create Date: 2025-04-20 12:05:45.605256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78fb89abfaa'
down_revision = 'c2caa668eb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tur_paketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('fiyat', sa.Float(), nullable=False),
    sa.Column('sure', sa.Integer(), nullable=True),
    sa.Column('kapasite', sa.Integer(), nullable=True),
    sa.Column('baslangic_bolge_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baslangic_bolge_id'], ['bolgeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tur_destinasyonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tur_paketi_id', sa.Integer(), nullable=False),
    sa.Column('destinasyon_id', sa.Integer(), nullable=False),
    sa.Column('siralama', sa.Integer(), nullable=True),
    sa.Column('kalma_suresi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destinasyon_id'], ['destinasyonlar.id'], ),
    sa.ForeignKeyConstraint(['tur_paketi_id'], ['tur_paketleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tur_seferleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tur_paketi_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_tarihi', sa.DateTime(), nullable=False),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=False),
    sa.Column('arac_id', sa.Integer(), nullable=True),
    sa.Column('rehber_id', sa.Integer(), nullable=True),
    sa.Column('sofor_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arac_id'], ['araclar.id'], ),
    sa.ForeignKeyConstraint(['rehber_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['sofor_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['tur_paketi_id'], ['tur_paketleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tur_seferleri')
    op.drop_table('tur_destinasyonlar')
    op.drop_table('tur_paketleri')
    # ### end Alembic commands ###
